### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by SunHui1216** [WenjunHuang94/ML-Mamba#3]
Thank you for your open source sharing of this wonderful work! I encountered difficulties while reading the code: I couldn't find the specific code implementation of Mamba-2 Scan Connector in the paper. If it's convenient, please give me some guidance. thank you!

**Comment by WenjunHuang94** [comment]
I have provided a detailed installation process description in the README under the Installation section. The implementation of the Mamba-2 Scan Connector can be found in the mamba repository that I further developed. You can follow these commands to access it:

`git clone https://github.com/WenjunHuang94/mamba`
`cd mamba && pip install -e .`

I hope this helps. Thank you!
